version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    # TODO Remove 'command' once the NAS is production-ready
    # This modified entry point enables logging and tracking of all postgres statements
    command: ["postgres", "-c", "log_statement=all", "-c", "shared_preload_libraries=pg_stat_statements", "-c", "track_activity_query_size=10000"]
    shm_size: '1gb'
    ports:
      - "${PG_EXPOSED_PORT-5432}:5432"
    environment:
      POSTGRES_DB: rdb
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./fixtures/postgres:/docker-entrypoint-initdb.d:ro

  pgadmin:
    image: dpage/pgadmin4:6.20
    ports:
      - "${PGADMIN_EXPOSED_PORT-3003}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "demo@example.com"
      PGADMIN_DEFAULT_PASSWORD: "demo123"
    depends_on:
      - postgres
    profiles:
      - tools

volumes:
  postgres-data:
